project:
  type: website

website:
  title: "DSAN-5000: Project"
  navbar:
    left:
      - href: Data/Data.qmd
        text: Data
      - href: Data/APIData.ipynb
        text: APIData
      - href: Code/Code.qmd
        text: Code
      - href: aboutme/aboutme.qmd
        text: About me
      - href: index.qmd
        text: Home
      - href: Data Gathering/Data Gathering.qmd
        text: Data Gathering
      - href: Data Cleaning/Data Cleaning.qmd
        text: Data Cleaning
      - href: eda/eda.qmd
        text: Data Exploration
      - href: Naïve Bayes/N_Bayes.qmd
        text: Naïve Bayes
      - href: clustering/clustering.qmd
        text: Clustering
      - href: Dimensionality reduction/Dimentionality.qmd
        text: Dimensionality reduction
      - href: Dicision Trees/Classification.qmd
        text: Classification
      - href: Dicision Trees/Regression.qmd
        text: Regression
      - href: ARM/ARM.qmd
        text: ARM
      - href: Conclusions/Conclusion.qmd
        text: Conclusion


format:
  html:
    theme: cosmo
    toc: true



