
## Clean up the data about proportion of electric cars owned by people of different genders and ages

[can find the data here](https://www.cso.ie/en/releasesandpublications/ep/p-smt/sustainablemobilityandtransport2021/electricvehicles/)

```{r}
library(readxl)
library(tidyverse)

#Read in the Data
data = read_excel("/Users/kenny/Desktop/dsan-5000-project-kennyzhao0428/dsan-website/5000-website/82.xlsx", skip = 2)

#Remove Unwanted Rows
df = data %>%
  mutate(Gender = case_when(
    `...1` == "Male" ~ "Male",
    `...1` == "Female" ~ "Female",
    TRUE ~ NA_character_
  ))
df = df %>%
  fill(Gender)

#Remove unnecessary rows
df = df %>%
  filter(!(`...1` %in% c("Male", "Female", "All Persons", "Sex/Age")))

#Fix the accuracy of numbers
df = df %>%
  mutate(`Electric Vehicle (EV) Ownership` = round(as.numeric(`Electric Vehicle (EV) Ownership`), 1))

#Rename columns
df = df %>%
  rename(
    `Age Group` = `...1`,
    `EV ownership Yes` = `Electric Vehicle (EV) Ownership`,
    `EV ownership No` = `...3`,
    Total = `...4`
  )

#Delete useless lines
df = df %>%
  slice(-c(1, 9))

print(df)
```



```{r}
library(readxl)
library(tidyverse)

#Read in the Data
data = read_excel("/Users/kenny/Desktop/dsan-5000-project-kennyzhao0428/dsan-website/5000-website/26.xlsx", skip = 2)

library(dplyr)

#Delete useless lines
df = data %>% filter(!apply(is.na(.), 1, all))

#Fix the accuracy of numbers
df = df %>%
  mutate(`...3` = round(as.numeric(`...3`), 1))%>%
  mutate(`...4` = round(as.numeric(`...4`), 1))%>%
  mutate(`...5` = round(as.numeric(`...5`), 1))%>%
  mutate(`...6` = round(as.numeric(`...6`), 1))%>%
  mutate(`...7` = round(as.numeric(`...7`), 1))%>%
  mutate(`...8` = round(as.numeric(`...8`), 1))%>%
  mutate(`...9` = round(as.numeric(`...9`), 1))%>%
  mutate(`...10` = round(as.numeric(`...10`), 1))%>%
  mutate(`...11` = round(as.numeric(`...11`), 1))%>%
  mutate(`...12` = round(as.numeric(`...12`), 1))

#Delete useless lines
df = df[-(17:20), ]

#rename
names(df)[1:ncol(df)] = c("Sex/Age group","Cost", "Inadequete public charging facilities", "No/limited access to home charging", "Limited range available", "Don't drive/ own a car", "Resale value of EV", "Reliability/ safety concerns", "No need/ don't know enough", "Not changing for a while", "Not available at time of last purchase", "Other", "Gender")

#Fix the accuracy of numbers
df = df %>%
  mutate(`Cost` = round(as.numeric(`Cost`), 1))

#Reshaping gender data
df = df %>%
  mutate(Gender = case_when(
    `Sex/Age group` == "Male" ~ "Male",
    `Sex/Age group` == "Female" ~ "Female",
    TRUE ~ NA_character_
  ))
df = df %>%
  fill(Gender)

#Delete useless lines
df = df %>%
  slice(-c(1, 3, 10))

print(df)
```

```{r}
df=read.csv("/Users/kenny/Desktop/dsan-5000-project-kennyzhao0428/data/01-modified-data/EVsalesHistori.csv")

```